Repository mondeja/leptos-fluent, pull requests merged in 2024-06, with the labels that each got.

#81 Add cookie support
  CHANGELOG.md
  Cargo.lock
  README.md
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/lib.rs
  leptos-fluent/src/localstorage.rs
  leptos-fluent/src/url.rs
Labels: new feature

#82 Drop `cfg-if` as macros dependency
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
Labels: enhancement, refactor

#83 Drop `I18n` implementation
  CHANGELOG.md
  README.md
  examples/csr-complete/src/lib.rs
  examples/csr-minimal/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: enhancement, refactor

#85 Add downloads badge to documentation
  README.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs

#86 Check translations at compile time
  .pre-commit-config.yaml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/locales/en/main.ftl
  examples/ssr-hydrate-axum/locales/es/main.ftl
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
  leptos-fluent/src/localstorage.rs
Labels: new feature

#91 Fix trait not in scope for translation macros
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#92 Fix error setting cookies
  CHANGELOG.md
  Cargo.lock
  README.md
  end2end/tests/TODO.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/lib.rs
Labels: bug

#93 Fix a lot of bugs in translations checker
  CHANGELOG.md
  Cargo.lock
  end2end/tests/TODO.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
Labels: bug

#94 Track locale and language files
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#96 Add more tests and refactor
  Cargo.toml
  end2end/tests-helpers/src/lib.rs
  end2end/tests/TODO.md
  end2end/tests/cookie.rs
  end2end/tests/csr_complete.rs
  end2end/tests/csr_minimal.rs
  end2end/tests/localstorage.rs
  end2end/tests/url_param.rs
  end2end/tests/url_param_to_localstorage.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/fluent_resources.rs
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/localstorage.rs
  leptos-fluent/src/url.rs
Labels: chore

#97 Report Fluent syntax errors
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/fluent_resources.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#101 Retry end2end tests on CI
  .github/workflows/ci.yml
Labels: chore

#102 Raise syn error instead of panic reading languages file
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/loader.rs
Labels: bug, enhancement

#103 Allow to read languages from a JSON5 file
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: new feature

#106 Add `core_locales` argument to `leptos_fluent!` macro
  CHANGELOG.md
  Cargo.lock
  README.md
  examples/csr-minimal/Cargo.toml
  examples/csr-minimal/src/lib.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: enhancement

#112 Get the initial language from URL parameter on SSR
  .pre-commit-config.yaml
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#117 Fix error building files tracker when multiple files for each language
  CHANGELOG.md
  Cargo.lock
  README.md
  examples/ssr-hydrate-actix/locales/en/404.ftl
  examples/ssr-hydrate-actix/locales/en/main.ftl
  examples/ssr-hydrate-actix/locales/es/404.ftl
  examples/ssr-hydrate-actix/locales/es/main.ftl
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#119 Fix parsing of raw string literals checking translations
  CHANGELOG.md
  README.md
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: bug

#120 Notify invalid Fluent message identifiers checking translations
  CHANGELOG.md
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
Labels: enhancement

#121 Document how to watch Fluent files with cargo-leptos
  README.md
  examples/ssr-hydrate-actix/Cargo.toml
  examples/ssr-hydrate-axum/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs

#122 Minor updates in documentation
  leptos-fluent-macros/src/lib.rs
Labels: docs

#123 Add `cookie_attrs` parameter to `leptos_fluent!` macro
  CHANGELOG.md
  Cargo.lock
  README.md
  end2end/tests/TODO.md
  end2end/tests/cookie.rs
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#124 Add `sync_html_tag_dir` parameter to `leptos_fluent!` macro
  CHANGELOG.md
  Cargo.lock
  README.md
  end2end/tests/csr_complete.rs
  examples/csr-complete/locales/en/main.ftl
  examples/csr-complete/locales/es/main.ftl
  examples/csr-complete/locales/languages.json
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/Cargo.toml
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/Cargo.toml
  examples/ssr-hydrate-axum/locales/languages.yaml
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: new feature

#125 A few performance optimizations
  .pre-commit-config.yaml
  README.md
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: enhancement, refactor

#129 Add support for multiple loaders in a single leptos_fluent! macro
  CHANGELOG.md
  README.md
  end2end/tests/cookie.rs
  end2end/tests/localstorage.rs
  end2end/tests/url_param.rs
  end2end/tests/url_param_to_localstorage.rs
  examples/csr-complete/src/lib.rs
  examples/csr-minimal/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: new feature

#130 Bump version and prepare v0.1
  CHANGELOG.md
  Cargo.lock
  README.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: chore

#128 Add book
  .github/workflows/ci.yml
  .markdown-link-check.json
  CONTRIBUTING.md
  README.md
  book/.gitignore
  book/book.toml
  book/src/SUMMARY.md
  book/src/basic-usage.md
  book/src/checking-translations.md
  book/src/install.md
  book/src/intro.md
  book/src/languages.md
  book/src/strategies.md
  end2end/tests/cookie.rs
  end2end/tests/localstorage.rs
  end2end/tests/url_param.rs
  end2end/tests/url_param_to_localstorage.rs
  examples/csr-complete/src/lib.rs
  examples/csr-minimal/Cargo.toml
  examples/csr-minimal/src/lib.rs
  examples/csr-minimal/src/main.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs

#131 Fix errors in docs
  book/src/basic-usage.md
  book/src/intro.md
  leptos-fluent/src/lib.rs
Labels: docs

#132 Improve linting config
  .pre-commit-config.yaml
  end2end/tests/url_param.rs
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/fluent_entries.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/lib.rs
Labels: chore

#133 Add method `activate` to `leptos_fluent::Language` struct
  CHANGELOG.md
  Cargo.lock
  book/src/basic-usage.md
  examples/csr-complete/src/lib.rs
  examples/csr-minimal/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: enhancement

#135 Validate cookie attributes when defined using string literals
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  book/src/checking-translations.md
  examples/csr-complete/src/lib.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/cookie.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
Labels: enhancement

#136 Add FAQs chapter to book
  book/src/SUMMARY.md
  book/src/basic-usage.md
  book/src/checking-translations.md
  book/src/faqs.md
  book/src/install.md
  book/src/intro.md
  examples/csr-complete/src/lib.rs
Labels: docs

#137 Fix errors in docs
  README.md
  book/src/checking-translations.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs

#139 Show locations of `tr!` macro spans when using a new `nightly` feature
  .github/actions/get-toolchain/action.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  examples/csr-complete/Cargo.toml
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/Cargo.toml
  rust-toolchain.toml
Labels: enhancement, new feature, nightly

#140 Add `initial_language_from_cookie_to_localstorage` to `leptos_fluent!`
  CHANGELOG.md
  README.md
  book/src/basic-usage.md
  book/src/faqs.md
  book/src/install.md
  book/src/strategies.md
  end2end/tests/cookie_to_localstorage.rs
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: new feature

#141 Fix `serde` dependency usage
  examples/csr-minimal/Cargo.toml
  leptos-fluent-macros/src/languages.rs
Labels: chore

#142 Better macro hygiene
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  book/src/intro.md
  book/src/languages.md
  leptos-fluent-macros/src/cookie.rs
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs, chore

#143 Handle errors reading Fluent resources
  .pre-commit-config.yaml
  book/src/intro.md
  leptos-fluent-macros/src/cookie.rs
  leptos-fluent-macros/src/fluent_resources.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/src/cookie.rs
Labels: chore

#144 Add missing metadata to crates
  .github/workflows/ci.yml
  .markdownlint-cli2.yaml
  Cargo.toml
  book/.gitignore
  book/book.toml
  end2end/Cargo.toml
  end2end/tests-helpers/Cargo.toml
  examples/csr-complete/Cargo.toml
  examples/csr-minimal/Cargo.toml
  examples/ssr-hydrate-actix/Cargo.toml
  examples/ssr-hydrate-axum/Cargo.toml
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
Labels: chore

#146 Don't use web_sys from leptos
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: bug

#147 Add `initial_language_from_localstorage_to_cookie` to `leptos_fluent!`
  CHANGELOG.md
  book/src/strategies.md
  end2end/tests/localstorage_to_cookie.rs
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#148 Allow to call the i18n context on nightly
  CHANGELOG.md
  book/src/basic-usage.md
  leptos-fluent/src/lib.rs
Labels: enhancement, nightly

#149 Prepare next release
  CHANGELOG.md
  README.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: chore

#150 Add server action example
  Cargo.lock
  book/src/faqs.md
  examples/ssr-hydrate-actix/locales/en/main.ftl
  examples/ssr-hydrate-actix/locales/es/main.ftl
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: docs

#151 Fix code highlight on book example
  book/src/faqs.md
Labels: docs

#153 Add `initial_language_from_navigator_to_localstorage` to `leptos_fluent!`
  CHANGELOG.md
  book/src/strategies.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: new feature

#154 Add `initial_language_from_navigator_to_cookie` to `leptos_fluent!`
  CHANGELOG.md
  book/src/strategies.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: new feature

#156 Produce less code on nightly with `leptos_fluent!`
  leptos-fluent-macros/src/lib.rs
Labels: enhancement

#157 Produce less code with `leptos_fluent!` macro
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/src/lib.rs
Labels: enhancement

#158 Prepare new release
  CHANGELOG.md
  README.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: chore

#159 Add `initial_language_from_system` to `leptos_fluent!`
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  end2end/tests/TODO.md
  examples/system-gtk/Cargo.toml
  examples/system-gtk/README.md
  examples/system-gtk/locales/en/main.ftl
  examples/system-gtk/locales/es/main.ftl
  examples/system-gtk/src/main.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: new feature

#160 Optimize builds with new parameter
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: refactor

#161 Add `SsrHtmlTag` component
  CHANGELOG.md
  Cargo.lock
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: new feature

#163 Allow persistent storage on desktop applications
  CHANGELOG.md
  Cargo.lock
  end2end/tests/TODO.md
  examples/system-gtk/src/main.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/data_file.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#164 Add examples of `leptos_fluent!` invocations to book
  book/src/basic-usage.md
  book/src/strategies.md
Labels: docs

#165 Use files tracker API on `nightly` to track files
  .gitattributes
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  book/book.toml
  book/mdbook-admonish.css
  book/src/SUMMARY.md
  book/src/basic-usage.md
  book/src/checking-translations.md
  book/src/faqs.md
  book/src/install.md
  book/src/languages.md
  book/src/leptos_fluent.md
  book/src/strategies.md
  examples/ssr-hydrate-axum/Cargo.toml
  examples/system-gtk/README.md
  examples/system-gtk/src/main.rs
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs, enhancement, nightly

#166 Improve reference chapter of the book
  book/src/feat.png
  book/src/leptos_fluent.md
Labels: docs

#167 Fix feature mark image in reference chapter of book
  book/src/feat.png
Labels: docs

#170 Allow to access `leptos_fluent!` parameter values at runtime
  .gitattributes
  CHANGELOG.md
  Cargo.lock
  examples/system-gtk/src/main.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/translations_checker/mod.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: enhancement

#171 Improvements for book
  book/src/basic-usage.md
  book/src/checking-translations.md
  book/src/faqs.md
  book/src/leptos_fluent.md
  book/src/strategies.md
Labels: docs

#172 Fix errors in book
  book/src/basic-usage.md
  book/src/install.md
  book/src/languages.md
Labels: docs

#173 Raise better error using `#[cfg( ... )]` before macro parameters
  book/src/basic-usage.md
  book/src/checking-translations.md
  book/src/faqs.md
  book/src/install.md
  book/src/strategies.md
  examples/ssr-hydrate-actix/Cargo.toml
  leptos-fluent-macros/src/loader.rs
Labels: bug

#174 Add emoji flags for countries
  CHANGELOG.md
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#175 Improvements in docs
  README.md
  book/src/leptos_fluent.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs

#176 Accept configuration conditional checks directly in most `leptos_fluent!` parameters
  CHANGELOG.md
  Cargo.lock
  book/src/faqs.md
  book/src/leptos_fluent.md
  examples/csr-minimal/src/lib.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: bug, enhancement

#177 Fix multiline configuration conditional checks
  Cargo.lock
  book/src/faqs.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
Labels: bug, docs

#178 Add server functions parameters to `leptos_fluent!`
  CHANGELOG.md
  book/src/strategies.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#179 Add `to_server_function` params for cookie and localstorage
  CHANGELOG.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#180 Add `initial_language_from_navigator_to_server_function` to `leptos_fluent!`
  CHANGELOG.md
  book/src/strategies.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#181 Add `initial_language_from_url_param_to_server_function` to `leptos_fluent!`
  CHANGELOG.md
  book/src/leptos_fluent.md
  book/src/strategies.md
  end2end/tests/TODO.md
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: docs, new feature

#182 Build examples with nightly toolchain on CI
  .github/actions/set-toolchain/action.yml
  .github/workflows/ci.yml
Labels: chore

#183 Add `initial_language_from_server_function_to_cookie` to `leptos_fluent!`
  CHANGELOG.md
  book/src/leptos_fluent.md
  book/src/strategies.md
  end2end/tests/TODO.md
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#184 Add `initial_language_from_server_function_to_localstorage` to `leptos_fluent!`
  CHANGELOG.md
  README.md
  book/src/intro.md
  book/src/leptos_fluent.md
  book/src/strategies.md
  end2end/tests/TODO.md
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: new feature

#185 Refactor macro params code
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: refactor

#186 Don't panic if no language name found
  book/src/install.md
  book/src/languages.md
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
Labels: enhancement
