Repository mondeja/leptos-fluent, pull requests merged in 2024-12, with the labels that each got.

#226 Remove deprecated component `SsrHtmlTag`
  Cargo.lock
  book/src/basic-usage.md
  book/src/faqs.md
  book/src/leptos_fluent.md
  examples/ssr-hydrate-actix/Cargo.toml
  examples/ssr-hydrate-axum/Cargo.toml
  examples/ssr-hydrate-axum/src/app.rs
  examples/ssr-islands-axum/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/translations_checker/tr_macros.rs
  leptos-fluent/src/lib.rs
Labels: chore, breaking

#227 No more default features
  CHANGELOG.md
  README.md
  book/src/install.md
  book/src/languages.md
  book/src/leptos_fluent.md
  examples/csr-complete/Cargo.toml
  examples/ssr-islands-axum/Cargo.toml
  examples/system-gtk/Cargo.toml
  leptos-fluent-macros/tests/ui/leptos_fluent/pass/compile_time_exprpath_target_predicate.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: enhancement, breaking

#244 Remove support for double braces in `leptos_fluent!` macro
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/tests/ui/leptos_fluent/fail/double_curly_braces.rs
  leptos-fluent-macros/tests/ui/leptos_fluent/fail/double_curly_braces.stderr
Labels: chore, breaking

#264 Update fluent-templates dependency to 0.12
  CHANGELOG.md
  Cargo.lock
  end2end/Cargo.toml
  examples/csr-complete/Cargo.toml
  examples/csr-minimal/Cargo.toml
  examples/ssr-hydrate-actix/Cargo.toml
  examples/ssr-hydrate-axum/Cargo.toml
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: bug

#268 Update docs to use fluent-templates v0.12
  Cargo.lock
  README.md
  book/src/basic-usage.md
  book/src/install.md
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
Labels: docs
