Repository mondeja/leptos-fluent, pull requests merged in 2024-10, with the labels that each got.

#247 Add `translations` field to `I18n`'s `Debug` implementation
  CHANGELOG.md
  leptos-fluent/src/lib.rs
Labels: enhancement

#246 Islands example
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  examples/ssr-islands-axum/Cargo.toml
  examples/ssr-islands-axum/README.md
  examples/ssr-islands-axum/locales/client/en/main.ftl
  examples/ssr-islands-axum/locales/client/es/main.ftl
  examples/ssr-islands-axum/locales/languages.json
  examples/ssr-islands-axum/locales/server/en/main.ftl
  examples/ssr-islands-axum/locales/server/es/main.ftl
  examples/ssr-islands-axum/public/favicon.ico
  examples/ssr-islands-axum/src/app.rs
  examples/ssr-islands-axum/src/error_template.rs
  examples/ssr-islands-axum/src/fileserv.rs
  examples/ssr-islands-axum/src/lib.rs
  examples/ssr-islands-axum/src/main.rs
  examples/ssr-islands-axum/style/main.css
Labels: docs

#253 Use lychee instead of markdown-link-check on CI
  .markdown-link-check.json
  .pre-commit-config.yaml
Labels: chore
