Repository mondeja/leptos-fluent, pull requests merged in 2025-08, with the labels that each got.

#358 Fix link to wasm-pack documentation
  CONTRIBUTING.md
Labels: chore

#355 Bump fluent syntax
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent/Cargo.toml
Labels: dependencies

#365 feat: Allow providing `customise` closure in `leptos_fluent!`
  examples/ssr-hydrate-actix/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/pass/complete.rs
  leptos-fluent/src/lib.rs
Labels: new feature

#366 Deprecate `disable-unicode-isolating-marks` feature
  CHANGELOG.md
  Cargo.lock
  book/src/leptos_fluent.md
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: chore
