Repository mondeja/leptos-fluent, pull requests merged in 2025-06, with the labels that each got.

#328 Reduce allocations in source parser of translations checker
  CHANGELOG.md
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/tr_macros.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/lib.rs
Labels: bug, performance

#338 Better book releasing strategy
  .github/workflows/ci.yml
Labels: docs

#339 Deprecate `Language`'s methods `is_active` and `activate`
  CHANGELOG.md
  book/src/advanced-usage.md
  book/src/basic-usage.md
  book/src/faqs.md
  book/src/install.md
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/src/lib.rs
  tests/end2end/tests/csr_minimal.rs
Labels: chore

#340 Deprecate parameters containing `localstorage` or `sessionstorage`
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  book/src/leptos_fluent.md
  book/src/strategies.md
  examples/csr-complete/src/lib.rs
  examples/ssr-hydrate-actix/src/app.rs
  examples/ssr-hydrate-axum/src/app.rs
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/pass/complete.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/README.md
  leptos-fluent/src/lib.rs
  leptos-fluent/src/local_storage.rs
  leptos-fluent/src/session_storage.rs
  tests/end2end/TODO.md
  tests/end2end/initial-language-from-navigator/tests/initial_language_from_navigator.rs
  tests/end2end/set-language-to-local-storage/Cargo.toml
  tests/end2end/set-language-to-local-storage/tests/set_language_to_localstorage.rs
  tests/end2end/set-language-to-local-storage/webdriver.json
  tests/end2end/set-language-to-session-storage/Cargo.toml
  tests/end2end/set-language-to-session-storage/tests/set_language_to_localstorage.rs
  tests/end2end/set-language-to-session-storage/webdriver.json
  tests/end2end/tests/cookie_to_local_storage.rs
  tests/end2end/tests/csr_complete.rs
  tests/end2end/tests/csr_minimal.rs
  tests/end2end/tests/local_storage.rs
  tests/end2end/tests/local_storage_to_cookie.rs
  tests/end2end/tests/local_storage_to_session_storage.rs
  tests/end2end/tests/session_storage.rs
  tests/end2end/tests/session_storage_to_cookie.rs
  tests/end2end/tests/session_storage_to_local_storage.rs
  tests/end2end/tests/url_param_to_local_storage.rs
  tests/end2end/tests/url_param_to_localstorage.rs
  tests/src/book.rs
  tests/src/leptos_fluent.rs
  tests/src/lib.rs
Labels: chore

#341 Canonicalize generated paths on stable
  CHANGELOG.md
  examples/csr-minimal/Cargo.toml
  leptos-fluent-macros/src/files_tracker.rs
  leptos-fluent-macros/src/fluent_resources.rs
  leptos-fluent-macros/src/loader.rs
Labels: enhancement

#343 Fix spans in error messages parsing `leptos_fluent!` inputs
  CHANGELOG.md
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/fail/double_curly_braces.stderr
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/fail/empty_parameter.stderr
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/fail/empty_value.stderr
  leptos-fluent-macros/tests/ui/leptos_fluent/stable/fail/invalid_str_as_litbool.stderr
Labels: enhancement

#346 Hygienize usages of re-exports
  CHANGELOG.md
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/languages.rs
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
  leptos-fluent/src/cookie.rs
  leptos-fluent/src/lib.rs
  leptos-fluent/src/url.rs
Labels: enhancement

#348 Don't continue translations checking when error parsing
  CHANGELOG.md
  leptos-fluent-macros/src/loader.rs
  leptos-fluent-macros/src/tr_macros.rs
  leptos-fluent-macros/src/translations_filler.rs
Labels: bug

#351 Fix `actix_web::HttpRequest` not longer provided in context
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  leptos-fluent-macros/Cargo.toml
  leptos-fluent-macros/src/lib.rs
  leptos-fluent/Cargo.toml
Labels: bug
